<?php $title = 'Acceuil'; ?>
<!-- demarre une tamporisation de sortie -->
<?php ob_start(); ?>

<section class="imgBack">
    <h1>BOERBULL MOTORS</h1>
</section>

<section class='sectionUniversel'>
    <h2>Choisissez une categorie de véhicules</h2>

    <div class='divNosCar'>  
        <?php foreach($home as $car_category): ?>

            <?php //pre_var_dump($car->get_name(), null, true) ?>

            <article class="<?= htmlspecialchars(htmlentities($car_category->{'name'})) ?>">
                <!-- il va envoyer le paramètre et la valeur category=super pour que CategoryController.class.php puisse le récupérer en $_GET[] -->
                <a href="index.php?action=category&id_category=<?= htmlspecialchars(htmlentities($car_category->get_id_category())) ?>">
                    <h3><?= $car_category->{'name'} ?></h3>
                    <div class="zoom">
                        <img src="www/imgBoerbullMotors/<?= htmlspecialchars(htmlentities($car_category->get_image_url())) ?>" 
                            alt="<?= htmlspecialchars(utf8_encode($car_category->get_modele())) ?>"
                        class='car'>
                    </div>
                </a>
            </article>
        <?php endforeach; ?>
    </div>
</section>

<!-- fermer la tamporisation de sortie et le mettre dans une variable -->
<?php $content = ob_get_clean(); ?>
<?php require_once 'www/layout/layoutView.phtml'; ?>