<?php $title = 'Inscription Admin'; ?>
<!-- demarre une tamporisation de sortie -->
<?php ob_start(); ?>
<section  class='sectionUniversel'>
    <h2>Inscription Admin</h2>

    <div class="divForm">
        <form action="index.php?action=admin&action2=registerAdmin" method="post" name="formulaire">
            <div>
                <!-- <label for='last_name'>Nom : </label> -->
                <input type='text' name='name' placeholder="Nom" id="lastName" required="required">
                    <span id="msgName"></span>
            </div>
            <div>
                <!-- <label for='mail'>Email : </label> -->
                <input type='text' name='mail' placeholder="Email" id='mail' required="required">
                    <span id="msgMail"></span>
            </div>
            <div>
                <!-- <label for='password'>Mot de passe : </label> -->
                <input type='password' name='password' placeholder="Mot de passe" id="password" required="required">
                    <span id="msgPass"></span>
            </div>
            <div>
                <!-- <label for='password'>Confirmez le Mot de passe : </label> -->
                <input type='password' name='password' placeholder="Mot de passe" required="required">
            </div>
            <div>
                <input type="submit" value="Enregistrer" class="myValid">
            </div>
            <p>
                Si vous ètes déjà inscrit : 
                    <a href="index.php?action=admin&action2=loginForm" id="klikici">cliquez ici</a>
            </p>
        </form>
    </div>
</section>
<!-- fermer la tamporisation de sortie et le mettre dans une variable -->
<?php $content = ob_get_clean(); ?>
<?php require_once 'www/layout/layoutView.phtml'; ?>