<?php $title = 'Une voiture'; ?>
<?php $userSession = new UserSession(); ?>
<?php $adminSession = new AdminSession(); ?>

<!-- demarre une tamporisation de sortie -->
<?php ob_start(); ?>

<section class='sectionUniversel'>

    <h2><?= htmlspecialchars(htmlentities($oneCar->get_marque())) . ' ' . htmlspecialchars(utf8_encode($oneCar->get_modele())) ?></h2>

    <div class='myImgCar zoom'>
        <img src="www/imgBoerbullMotors/<?= $oneCar->get_image_url() ?>"  alt="<?= htmlspecialchars(utf8_encode($oneCar->get_modele())) ?>" class="myImgOneCar"> 
    </div><!--  
    
--><div class='myStatCar'>
        <ul>
            <li><strong>Marque : </strong><?= htmlspecialchars(htmlentities($oneCar->get_marque())) ?></li>
            <li><strong>Modèle : </strong><?= htmlspecialchars(utf8_encode($oneCar->get_modele())) ?></li>
            <li><strong>Année : </strong><?= htmlspecialchars(htmlentities($oneCar->get_annee())) ?></li>
            <li><strong>Conso : </strong><?= htmlspecialchars(htmlentities($oneCar->get_conso())) ?> L/100 km</li>
            <li><strong>Couleur : </strong><?= htmlspecialchars(htmlentities($oneCar->get_color())) ?></li>
            <li><strong>Puissance : </strong><?= htmlspecialchars(htmlentities($oneCar->get_puissance())) ?> ch</li>
            <li><strong>Moteur : </strong><?= htmlspecialchars(htmlentities($oneCar->get_moteur())) ?> cylindre</li>
            <li><strong>Carburant : </strong><?= htmlspecialchars(htmlentities($oneCar->get_carburant())) ?></li>
            <li><strong>0-100 KM : </strong><?= htmlspecialchars(htmlentities($oneCar->get_cent())) ?> secondes</li>
            <li><strong>Nombre de place : </strong><?= htmlspecialchars(htmlentities($oneCar->get_nombre_de_place())) ?></li>
            <li><strong>Prix pour 3 jours : </strong><?= htmlspecialchars(htmlentities($oneCar->get_prix_trois_jours())) ?> € hors taxe</li>
        </ul>


        
        <?php if (!$adminSession->isAuthenticatedAdmin()) : ?>
            <!-- si on est pas connecter le , Ajouter au panier , nous emmènera vers la page login  -->
            <?php if (!$userSession->isAuthenticatedUser()) : ?>
                <button><a href="index.php?action=user&action2=loginForm" onclick="return seConnecter()">Ajouer au panier</a></button>
            <?php else : ?>    
                <button><a href="index.php?action=panier&id=<?= htmlspecialchars(htmlentities($oneCar->get_id())) ?>">Ajouter au panier</a></button>
            <?php endif; ?>
        <?php else : ?> 

        <?php endif; ?>
    </div>
</section>
<!-- fermer la tamporisation de sortie et le mettre dans une variable -->
<?php $content = ob_get_clean(); ?>
<?php require_once 'www/layout/layoutView.phtml'; ?>



