<?php $title = 'modifier client'; ?>
<!-- demarre une tamporisation de sortie -->
<?php ob_start(); ?>

<section class='sectionUniversel'>
    <h2>Modifier</h2>
    
    <form action='index.php?action=admin&action2=users&action3=edit' method='post'>

        <div>
            <input type="hidden" value="<?= htmlspecialchars(htmlentities($adminEditFormUsers[0]['id'])) ?>" name="id">
        </div>    

        <div>
            <label for='last_name'>Nom : </label>
            <input type='text' value="<?= htmlspecialchars(utf8_encode($adminEditFormUsers[0]['last_name'])) ?>" id="lastName" name="last_name">
            <span id="msgName"></span>
        </div>

        <div>
            <label for='first_name'>Prénom : </label>
            <input type='text' value="<?= htmlspecialchars(utf8_encode($adminEditFormUsers[0]['first_name'])) ?>" id="firstName" name="first_name">
            <span id="msgFirstName"></span>
        </div>    

        <div>
            <label for='mail'>Mail : </label>
            <input type='text' value="<?= htmlspecialchars(htmlentities($adminEditFormUsers[0]['mail'])) ?>" id='mail' name="mail">
            <span id="msgMail"></span>
        </div>

        <div>
            <label for='password'>Mot de passe : </label>
            <input type='password' name='password'  id="password">
            <span id="msgPass"></span>
        </div>    

        <div>
            <input type='submit' value='Enregistrer' class="myValid">
        </div>
    </form>
</section>
<!-- fermer la tamporisation de sortie et le mettre dans une variable -->
<?php $content = ob_get_clean(); ?>
<?php require_once 'www/layout/layoutView.phtml'; ?>