<?php $title = 'Connexion'; ?>
<!-- demarre une tamporisation de sortie -->
<?php ob_start(); ?>
<section class='sectionUniversel'>

    <h2>Connexion</h2>

    <!-- <button><a href="index.php?action=user&action2=registerForm">INSCRIPTION</a></button> -->

    <div class="divForm">
        <form action="index.php?action=user&action2=login" method="post" id="form" name="formulaire" >
            <div>
                <input type='text' name='mail' id='mail' placeholder="Email" class="myInput" required>
                    <span id="msgMail"></span>
            </div>
            <div>
                <input type='password' name='password' id="password" placeholder="Mot de passe" class="myInput" required>
                    <span id="msgPass"></span>
            </div>
            <div>
                <input type="submit"  value="Valider" class="myValid">
            </div>

            <p>
                Si vous n'ètes pas inscrit : 
                    <a href="index.php?action=user&action2=registerForm" id="klikici">cliquez ici</a>
            </p>
        </form>
    </div>
   
</section>

<!-- fermer la tamporisation de sortie et le mettre dans une variable -->
<?php $content = ob_get_clean(); ?>
<?php require_once 'www/layout/layoutView.phtml'; ?>