<?php $title = 'categories'; ?>
<!-- demarre une tamporisation de sortie -->
<?php ob_start(); ?>
<section class='sectionUniversel'>

<?php //pre_var_dump('L 6, CategoryView.php ', $categories['0']->{'name'}, true);?>
    <h2>Category : <?= htmlspecialchars(htmlentities($cars_by_category['0']->{'name'})) ?></h2>
    
    <div class='divCategory'>

        <?php foreach($cars_by_category as $value): ?> 
            <a href="index.php?action=oneCar&id=<?= htmlspecialchars(htmlentities($value->get_id())) ?>">
                <div class='zoom'>
                    <img src="www/imgBoerbullMotors/<?= htmlspecialchars(htmlentities($value->get_image_url())) ?>"  
                        height="250" width="350" alt="<?= htmlspecialchars(utf8_encode($value->get_modele())) ?>">
                </div> 
                <p><?= htmlspecialchars(htmlentities($value->get_marque())) . ' ' . htmlspecialchars(utf8_encode($value->get_modele())) ?></p>
            </a>  
        <?php endforeach ?> 

    </div>    

</section>
<!-- fermer la tamporisation de sortie et le mettre dans une variable -->
<?php $content = ob_get_clean(); ?>
<?php require_once 'www/layout/layoutView.phtml'; ?>