<?php $title = 'Ajouter une voiture'; ?>
<!-- demarre une tamporisation de sortie -->
<?php ob_start(); ?>

<section class='sectionUniversel'>
    <h2>Ajouter une voiture</h2>

    <div class='divForm'>

        <div id="error"><span></span></div>

        <form action="index.php?action=admin&action2=car&action3=add" method="post" id="form_car" name="formulaire">

            <div>
                <label for="marque">Marque : </label>
                <input type="text" name="marque" required>
            </div>

            <div>
                <label for="modele">Modèle : </label>
                <input type="text" name="modele" required>
            </div>

            <div>
                <label for="annee">Année : </label>
                <input type="text" name="annee" required>
            </div>

            <div>
                <label for="conso">Conso : </label>
                <input type="text" name="conso" required>
            </div>

            <div>
                <label for="color">Couleur : </label>
                <input type="text" name="color" required>
            </div>

            <div>
                <label for="puissance">Puissance : </label>
                <input type="text" name="puissance" required>
            </div>

            <div>
                <label for="moteur">Moteur : </label>
                <input type="text" name="moteur" required>
            </div>  

            <div>
                <label for="carburant">Carburant : </label>
                <input type="text" name="carburant" required>
            </div>

            <div>
                <label for="cent">0-100 KM : </label>
                <input type="text" name="cent" required>
            </div>

            <div>
                <label for="nombre_de_place">Nombre de place : </label>
                <input type="text" name="nombre_de_place" required>
            </div>

            <div>
                <label for="prix_trois_jours">Prix pour 3 jours : </label>
                <input type="text" name="prix_trois_jours" required>
            </div>

            <div>
                <label for="image_url">Adresse de l'image : </label>
                <input type="text" name="image_url" required>
            </div>

            <div>
                <label for="id_category">Categories</label>
                <!-- je met le name="id_category" dans le select pour qu'il soit pris en compte lors de l'insertion dans la bdd-->
                <select id="id_category"  name="id_category" required>
                    <option value=" ">Choisir une categorie</option>
                    <?php foreach($category as $value): ?>
                        <option value="<?= $value['id'] ?>"><?= htmlspecialchars(htmlentities($value['name'])) ?></option>
                    <?php endforeach ; ?> 
                </select>
            </div>

            <div>
                <input type="submit" value="Enregistrer" class="myValid">
            </div>
        </form>
    </div>
</section>
<!-- fermer la tamporisation de sortie et le mettre dans une variable -->
<?php $content = ob_get_clean(); ?>
<?php require_once 'www/layout/layoutView.phtml'; ?>