<?php $title = 'A Propos'; ?>
<!-- demarre une tamporisation de sortie -->
<?php ob_start(); ?>

<section class='sectionUniversel '>
    <h2>A propos de nous</h2>

    <p>Nous somme une société qui s'occupe de loyer des voitures de luxe<br>

        Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, praesentium? Amet, suscipit! Vero obcaecati eius excepturi in omnis laudantium, aperiam placeat suscipit itaque dolorum rerum nobis, tempore fugit quod aut!<br>
        Id iusto eaque voluptas laudantium nulla libero beatae. Quo ipsam illum eligendi ut nobis possimus veniam, suscipit natus, praesentium qui quae eum soluta minima nam magnam commodi. Laudantium, aspernatur nisi!<br>
        Quos at impedit modi molestiae repellendus saepe aperiam. Iure tempora error saepe. Reprehenderit libero recusandae quisquam ab, voluptatem cupiditate tenetur commodi animi. Dignissimos, ipsum? Tenetur accusantium provident corporis dignissimos reiciendis?<br>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, praesentium? Amet, suscipit! Vero obcaecati eius excepturi in omnis laudantium, aperiam placeat suscipit itaque dolorum rerum nobis, tempore fugit quod aut!<br>
        Id iusto eaque voluptas laudantium nulla libero beatae. Quo ipsam illum eligendi ut nobis possimus veniam, suscipit natus, praesentium qui quae eum soluta minima nam magnam commodi. Laudantium, aspernatur nisi!<br><br>
        Quos at impedit modi molestiae repellendus saepe aperiam. Iure tempora error saepe. Reprehenderit libero recusandae quisquam ab, voluptatem cupiditate tenetur commodi animi. Dignissimos, ipsum? Tenetur accusantium provident corporis dignissimos reiciendis?<br>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, praesentium? Amet, suscipit! Vero obcaecati eius excepturi in omnis laudantium, aperiam placeat suscipit itaque dolorum rerum nobis, tempore fugit quod aut!<br>
        Id iusto eaque voluptas laudantium nulla libero beatae. Quo ipsam illum eligendi ut nobis possimus veniam, suscipit natus, praesentium qui quae eum soluta minima nam magnam commodi. Laudantium, aspernatur nisi!<br>
        Quos at impedit modi molestiae repellendus saepe aperiam. Iure tempora error saepe. Reprehenderit libero recusandae quisquam ab, voluptatem cupiditate tenetur commodi animi. Dignissimos, ipsum? Tenetur accusantium provident corporis dignissimos reiciendis?<br>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, praesentium? Amet, suscipit! Vero obcaecati eius excepturi in omnis laudantium, aperiam placeat suscipit itaque dolorum rerum nobis, tempore fugit quod aut!<br>
        Id iusto eaque voluptas laudantium nulla libero beatae. Quo ipsam illum eligendi ut nobis possimus veniam, suscipit natus, praesentium qui quae eum soluta minima nam magnam commodi. Laudantium, aspernatur nisi!<br><br>
        Quos at impedit modi molestiae repellendus saepe aperiam. Iure tempora error saepe. Reprehenderit libero recusandae quisquam ab, voluptatem cupiditate tenetur commodi animi. Dignissimos, ipsum? Tenetur accusantium provident corporis dignissimos reiciendis?<br>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, praesentium? Amet, suscipit! Vero obcaecati eius excepturi in omnis laudantium, aperiam placeat suscipit itaque dolorum rerum nobis, tempore fugit quod aut!<br>
        Id iusto eaque voluptas laudantium nulla libero beatae. Quo ipsam illum eligendi ut nobis possimus veniam, suscipit natus, praesentium qui quae eum soluta minima nam magnam commodi. Laudantium, aspernatur nisi!<br>
        Quos at impedit modi molestiae repellendus saepe aperiam. Iure tempora error saepe. Reprehenderit libero recusandae quisquam ab, voluptatem cupiditate tenetur commodi animi. Dignissimos, ipsum? Tenetur accusantium provident corporis dignissimos reiciendis?<br>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, praesentium? Amet, suscipit! Vero obcaecati eius excepturi in omnis laudantium, aperiam placeat suscipit itaque dolorum rerum nobis, tempore fugit quod aut!<br>
        Id iusto eaque voluptas laudantium nulla libero beatae. Quo ipsam illum eligendi ut nobis possimus veniam, suscipit natus, praesentium qui quae eum soluta minima nam magnam commodi. Laudantium, aspernatur nisi!<br><br>
        Quos at impedit modi molestiae repellendus saepe aperiam. Iure tempora error saepe. Reprehenderit libero recusandae quisquam ab, voluptatem cupiditate tenetur commodi animi. Dignissimos, ipsum? Tenetur accusantium provident corporis dignissimos reiciendis?<br>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, praesentium? Amet, suscipit! Vero obcaecati eius excepturi in omnis laudantium, aperiam placeat suscipit itaque dolorum rerum nobis, tempore fugit quod aut!<br>
        Id iusto eaque voluptas laudantium nulla libero beatae. Quo ipsam illum eligendi ut nobis possimus veniam, suscipit natus, praesentium qui quae eum soluta minima nam magnam commodi. Laudantium, aspernatur nisi!<br>
        Quos at impedit modi molestiae repellendus saepe aperiam. Iure tempora error saepe. Reprehenderit libero recusandae quisquam ab, voluptatem cupiditate tenetur commodi animi. Dignissimos, ipsum? Tenetur accusantium provident corporis dignissimos reiciendis?<br>

    </p>
</section>
<!-- fermer la tamporisation de sortie et le mettre dans une variable -->
<?php $content = ob_get_clean(); ?>
<?php require_once 'www/layout/layoutView.phtml'; ?>